### ISSUE TITLE
Error initializing process due to the inability to get startup parameters from the named init_file

### ISSUE THREAD

**Issue by eeid26** [jppop/dctm-docker#3]
Not sure why I am getting the error shown in the log when I try to run
docker run -dP -p 1489:1489 -p 49000:49000 --name dctm-cs -h dctm-cs --link dbora:dbora dctm-cs
See the log below.

FYI, The create images logs in ./dctm-docker/logs all have Successfully built

``` html
Starting the Connection broker
Installing the repository devbox (    2822256)
Preparing to install...
Extracting the installation resources from the installer archive...
2015-03-31T00:36:29.630243 [DM_DOCBROKER_I_START]info:  "Docbroker has started.  Process id: 11"
2015-03-31T00:36:29.637148 [DM_DOCBROKER_I_REGISTERED_PORT]info:  "The Docbroker registered using port (1489)."
2015-03-31T00:36:29.637327 [DM_DOCBROKER_I_LISTENING]info:  "The Docbroker is listening on network address: (INET_ADDR: family: 2, port: 1489, host: dctm-cs (172.17.0.114, 720011ac))"
Configuring the installer for this system's environment...

Launching installer...

done
Create BAM database owner..

User created.


Grant succeeded.

Stopping the repository
Starting the repository devbox..
+ starting jms in background..
2015-03-31T00:37:16.233056  252[252]    0000000000000000    [DM_SERVER_E_INI_FILE_ACCESS]error:  "Error initializing process due to the inability to get startup parameters from the named init_file: /opt/documentum/dba/config/devbox/server.ini.  Error reason:  errno: 2, message: No such file or directory."

Usage: ./documentum -docbase_name <docbase name> -init_file <filename> [-o<option>]

    -docbase_name : name of docbase
    -init_file    : name of server.ini file (including path) which
                    contains the server startup parameters

Usage: ./documentum -h 

```

**Comment by jppop** [comment]
Could you check the content server installation logs. They are located in `/opt/documentum/product/7.1/install`.
If the container is still running (which i doubt):

``` bash
docker exec -it dctm-cs bash
cd $DM_HOME/install
ls -ltr
```

If the container have stopped:

``` bash
docker cp dctm-cs:/opt/documentum/product/7.1/install/logs /any/path
docker cp dctm-cs:/opt/documentum/product/7.1/install/dmadmin.ServerConfigurator.log /any/path
```

Please check also the disk space left on the host running docker.

**Comment by eeid26** [comment]
yes the machine was not running 
There is an error in the
dctm-cs:/opt/documentum/product/7.1/install/logs/install.log

``` html
16:13:09,868  INFO [main] com.documentum.install.server.installanywhere.actions.DiWAServerLoadDataFileInfo - The installer will set default database information for repository devbox.
16:13:09,884  INFO [main] com.documentum.install.server.installanywhere.actions.DiWAServerCheckProcessXHive - processing xhive=false
16:13:09,894  INFO [main] com.documentum.install.server.installanywhere.actions.DiWAServerModifyDfcProperties - The installer will update dfc.properties file.
16:13:09,900  INFO [main] com.documentum.install.shared.common.services.dfc.DiDfcProperties - Installer is adding it as primary connection broker and moves existing primary as backup.
16:13:09,913 ERROR [main] com.documentum.install.server.installanywhere.actions.DiWAServerModifyDfcProperties - Failed to backup file: /opt/documentum/shared/config/dfc.properties - current user may lack adequate security access privileges. Click Yes to continue,click NO to exit from the installer.
com.documentum.install.shared.common.error.DiException: Failed to backup file: /opt/documentum/shared/config/dfc.properties - current user may lack adequate security access privileges.
    at com.documentum.install.shared.common.services.DiUtil.backupFile(DiUtil.java:1866)
    at com.documentum.install.shared.common.services.DiProperties.flush(DiProperties.java:394)
    at com.documentum.install.shared.common.services.DiProperties.flush(DiProperties.java:373)
    at com.documentum.install.shared.common.services.dfc.DiDfcProperties.commit(DiDfcProperties.java:93)
    at com.documentum.install.server.installanywhere.actions.DiWAServerModifyDfcProperties.modifyDfcProperties(DiWAServerModifyDfcProperties.java:63)
    at com.documentum.install.server.installanywhere.actions.DiWAServerModifyDfcProperties.setup(DiWAServerModifyDfcProperties.java:48)
    at com.documentum.install.shared.installanywhere.actions.InstallWizardAction.install(InstallWizardAction.java:75)
    at com.zerog.ia.installer.actions.CustomAction.installSelf(DashoA10*..)
```

**Comment by jppop** [comment]
Sorry, I can't reproduce the issue. I have successfully created a new container.
Did you check the disk space ?
You should create again the images (dctm-base and dctm-cs) :

``` bash
docker build --no-cache -t dctm-base dctm-base/
docker build --no-cache -t dctm-cs dctm-cs/
```

**Comment by eeid26** [comment]
Thank you for your help. it was some crazy windows / Unix chars in one of the files I modified. I have it working now.

Excellent work.

**Comment by jppop** [comment]
thanks
